version: '3.5'
services:

  automation:
    stdin_open: true
    tty: true
    container_name: lkaf
    networks:
      devotv-lkaf:
        aliases:
          - lkaf.dev
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: dev-automation
    working_dir: /repo/automation
    command: /bin/sh
    volumes:
      - './:/repo/automation:delegated'
      - './docker/:/docker:delegated'
      - './output:/repo/automation/output'
      - './reports:/repo/automation/reports'
networks:
  devotv-lkaf:
    name: devotv-lkaf